//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_DWH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_ExternalObjectFields
    {
        public int dd_exobjfl_id { get; set; }
        public Nullable<int> dd_exobj_id { get; set; }
        public string dd_exobjfl_name { get; set; }
        public string dd_exobjfl_description { get; set; }
        public string dd_exobjfl_dataType { get; set; }
        public string dd_exobjfl_length { get; set; }
        public Nullable<System.DateTime> dd_exobjfl_modificationDate { get; set; }
        public string dd_exobjfl_parentAttribute { get; set; }
        public string dd_exobjfl_childAttribute { get; set; }
        public Nullable<int> dd_lclobjFl_id { get; set; }
        public string dd_exobjfl_parameter { get; set; }
        public Nullable<bool> dd_exobjfl_isPrimaryKey { get; set; }
        public Nullable<bool> dd_exobjfl_isForeignKey { get; set; }
        public string dd_exobjfl_attrKey { get; set; }
        public string dd_exobjfl_attrValue { get; set; }
    
        public virtual DD_ExternalObject DD_ExternalObject { get; set; }
        public virtual DD_LocalObjectFields DD_LocalObjectFields { get; set; }
    }
}
