//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_DWH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_LocalObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_LocalObject()
        {
            this.DD_ExternalObject = new HashSet<DD_ExternalObject>();
            this.DD_LocalObjectFields = new HashSet<DD_LocalObjectFields>();
        }
    
        public int dd_lclobj_id { get; set; }
        public string dd_lclobj_name { get; set; }
        public string dd_lclbj_description { get; set; }
        public Nullable<System.DateTime> dd_lclobj_modificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_ExternalObject> DD_ExternalObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_LocalObjectFields> DD_LocalObjectFields { get; set; }
    }
}
