//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_DWH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_LocalObjectFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_LocalObjectFields()
        {
            this.DD_ExternalObjectFields = new HashSet<DD_ExternalObjectFields>();
        }
    
        public int dd_lclobjfl_id { get; set; }
        public Nullable<int> dd_lclobj_id { get; set; }
        public string dd_lclobjfl_name { get; set; }
        public string dd_lclobjfl_description { get; set; }
        public string dd_lclobjfl_dataType { get; set; }
        public string dd_lclobjfl_length { get; set; }
        public Nullable<System.DateTime> dd_lclobjfl_modificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_ExternalObjectFields> DD_ExternalObjectFields { get; set; }
        public virtual DD_LocalObject DD_LocalObject { get; set; }
    }
}
