//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_DWH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalApplication()
        {
            this.ConfigExternalApplication = new HashSet<ConfigExternalApplication>();
            this.DD_ExternalObject = new HashSet<DD_ExternalObject>();
        }
    
        public int exap_id { get; set; }
        public string exap_name { get; set; }
        public string exap_description { get; set; }
        public Nullable<int> cnnt_id { get; set; }
        public Nullable<bool> exap_state { get; set; }
        public Nullable<System.DateTime> exap_registrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigExternalApplication> ConfigExternalApplication { get; set; }
        public virtual ConnectionType ConnectionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_ExternalObject> DD_ExternalObject { get; set; }
    }
}
